server:
  port: 8081

spring:
  application:
    name: portal

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:cargo_flow_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

  flyway:
    clean-on-validation-error: true
    clean-disabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://127.0.0.1:8080}
  realm: ${KEYCLOAK_REALM:cargo-flow}
  client-id: ${KEYCLOAK_CLIENT_ID:portal-service}
  username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:qwe123}

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG