server:
  port: 8081

spring:
  application:
    name: portal

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://127.0.0.1:8080}
  realm: ${KEYCLOAK_REALM:cargo-flow}
  client-id: ${KEYCLOAK_CLIENT_ID:gateway-service}
  principle-attribute: preferred_username
  username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:qwe123}
  auth-path: /realms/${keycloak.realm}/protocol/openid-connect/token