server:
  port: 8090

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${keycloak.auth-server-url}
          predicates:
            - Path=/openid-connect/**
          filters:
            - RewritePath=/openid-connect,/realms/${keycloak.realm}/protocol/openid-connect

        - id: portal
          uri: lb://portal
          predicates:
            - Path=/portal/**

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://127.0.0.1:8080}
  realm: ${KEYCLOAK_REALM:cargo-flow}
  client-id: ${KEYCLOAK_CLIENT_ID:gateway-service}
  username: ${KEYCLOAK_ADMIN_USERNAME:realm_admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:1234}