server:
  port: 8083

spring:
  application:
    name: driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_URL:localhost:29092}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://127.0.0.1:8080}
  realm: ${KEYCLOAK_REALM:cargo-flow}

cargo-flow-starter:
  logist-url: http://logist/logist/v1

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG