server:
  port: 8082

spring:
  application:
    name: logist

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:cargo_flow_db}?currentSchema=logist_schema
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

  flyway:
    clean-on-validation-error: true
    clean-disabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://127.0.0.1:8080}
  realm: ${KEYCLOAK_REALM:cargo-flow}

cargo-flow-starter:
  portal-url: http://portal/portal/v1

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG