server:
  port: 8084

spring:
  application:
    name: dwh

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: ${MONGO_DB_NAME:cargo_flow_db}
      auto-index-creation: true
      username: ${MONGO_DB_USERNAME:mongo}
      password: ${MONGO_DB_PASSWORD:mongo}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_URL:localhost:29092}
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    company_statistics:
      name: ${KAFKA_COMPANY_STATISTICS_TOPIC_NAME:company_statistics_topic}
      group: ${KAFKA_COMPANY_STATISTICS_GROUP_NAME:company_statistics_group}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://127.0.0.1:8080}
  realm: ${KEYCLOAK_REALM:cargo-flow}

cargo-flow-starter:
  service-name: DWH_SERVICE

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG